### PR TITLE
Set http headers and status code only if partial content

### PR DESCRIPTION
**Pull request by peveuve**
generate status code 206 and HTP headers if result actually paginated,
generate default status code and no headers if the whole result is returned in one page.

### CODE REVIEW

**Comment by fknop** [comment]
Could you explain all the changes you've made before reviewing? I see multiple commits.

**Comment by peveuve** [comment]
My bad, I shouldn't have committed the second one.

The purpose of the second commit is to force pagination, so prevent the caller from disabling pagination with the query parameter "pagination". Some routes have thousands of records and we simply can't allow to disable pagination.
So I propose to add an active flag in the config which would work similarly to the one you have in the meta config. Default value would be true to remain consistent with today's behavior.

The third commit is a small fix in ext.js: do not send pagination status code and headers if the requested range is out of bounds (let the application returns a 416 or other meaningful code).

**Comment by fknop** [comment]
Thanks for the explanation. I didn't look at the code yet. Could the active option solve https://github.com/fknop/hapi-pagination/issues/19 ? Or it's only for the query parameter ?

I'm probably gonna review this tomorrow if that's ok with you.

**Comment by peveuve** [comment]
I don't think it solves the issue #19, my change is just a way to prevent the caller from enabling or disabling the pagination if you want to keep the control on this.

You can review the code tomorrow, it's fine.

**Review by fknop — APPROVED** [review]
Looks good.

**Pull request merged**
