### PR TITLE
Added the possibility to change reply parameters names and added the ability to use the offset value from 0 

### PR DESCRIPTION
**Pull request by czerwonkabartosz**

### CODE REVIEW

**Comment by fknop** [comment]
Could you explain your issue with the changed name of result ?

The `source.results` is supposed to be for the results returned with the decorate method (https://github.com/fknop/hapi-pagination/blob/master/lib/decorate.js#L28).

Also, it looks like a test is failing.

**Comment by czerwonkabartosz** [comment]
I fixed tests and added test explaining the problem.

I have problem with pagination when I want to use in this approach:
`reply({rows:[], count:0})`

Not always wants to transmit to reply object with the field `results`.

**Comment by czerwonkabartosz** [comment]
This problem came to me when I wanted to use this pagination (http://docs.sequelizejs.com/en/latest/docs/models-usage/#findandcountall-search-for-multiple-elements-in-the-database-returns-both-data-and-total-count) and pass it immediately to reply (without mapping fields).

**Comment by fknop** [comment]
Looks like the tests are fine now. I'm going to publish this later, thanks.

**Comment by czerwonkabartosz** [comment]
@fknop I changed my approach and added to the reply option to change the parameter names. I think it would be a better option.

**Comment by fknop** [comment]
Published.

**Comment by czerwonkabartosz** [comment]
Nice ! 👍

**Pull request merged**
