### PR TITLE
Added support for multi connections

### PR DESCRIPTION
**Pull request by czerwonkabartosz**
The library has a problem with handling multiple connections.
The problem was that the library has always used the last settings - it was not possible to have a separate connection settings.

I created new PR, because there was actually too much clutter. Sorry.

### CODE REVIEW

**Comment by czerwonkabartosz** [comment]
@fknop And what do you think ? For me it's working very good, but I prefer to ask creator of this lib.

**Comment by fknop** [comment]
Didn't really have the time to look at it today. It looks good for me at first glance. I'll probably merge it tomorrow (it's late).

**Comment by fknop** [comment]
I had to revert the change, the tests do not pass every time: 

For the connection 1 test I have the results from the second connection.

```
{ metaConnection2:
   { count: 20,
     pageCount: 1,
     totalCount: 20,
     next: null,
     self: 'http://localhost/users?page=1&limit=25',
     previous: null,
     first: 'http://localhost/users?page=1&limit=25',
     last: 'http://localhost/users?page=1&limit=25' },
  connection2:
   [ { name: 'name0', username: 'username0' },
     { name: 'name1', username: 'username1' },
     { name: 'name2', username: 'username2' },
     { name: 'name3', username: 'username3' },
     { name: 'name4', username: 'username4' },
     { name: 'name5', username: 'username5' },
     { name: 'name6', username: 'username6' },
     { name: 'name7', username: 'username7' },
     { name: 'name8', username: 'username8' },
     { name: 'name9', username: 'username9' },
     { name: 'name10', username: 'username10' },
     { name: 'name11', username: 'username11' },
     { name: 'name12', username: 'username12' },
     { name: 'name13', username: 'username13' },
     { name: 'name14', username: 'username14' },
     { name: 'name15', username: 'username15' },
     { name: 'name16', username: 'username16' },
     { name: 'name17', username: 'username17' },
     { name: 'name18', username: 'username18' },
     { name: 'name19', username: 'username19' } ] }
Debug: internal, implementation, error
    Error: Expected undefined to be an array but got 'undefined'
```

Coud you please look into it and open another PR when it's done?

**Comment by czerwonkabartosz** [comment]
I made a lot of tests, and for me this error does not occur.

**Comment by czerwonkabartosz** [comment]
Your error occurred earlier, before my changes. You are sure that a good version you tested?

**Comment by fknop** [comment]
Yes, but the error doesn't occur every time.

**Comment by czerwonkabartosz** [comment]
How often do you get?

**Comment by fknop** [comment]
One on five - ten, it depends.

**Comment by czerwonkabartosz** [comment]
But it is impossible to happen. See here - https://github.com/fknop/hapi-pagination/pull/17/files#diff-6a0485bb0c7f388287d612e89f54d33eR13 . It is not possible to use different configuration.

**Comment by czerwonkabartosz** [comment]
Which version of Node.js do you have?

**Comment by fknop** [comment]
v5.5.0

**Comment by czerwonkabartosz** [comment]
I can't repeat this error...

**Comment by fknop** [comment]
I'm going to pull and try again later... 

I believe the `server.ext('onPreHandler', ...)` called twice is causing this.
I'm not sure if it registers it for the routes on this connection only.

**Comment by fknop** [comment]
I asked on Gitter: 

```
Hi, when we're calling server.ext('onPreHandler', ...) in a plugin registered by a connection. Is the prehandler registered only for this connection or for the all server ?

@fknop all known connections at the moment of your registration
```

So I guess it means that the second prehandler could run after depending on the order of the executed promises when you register the plugins.

**Comment by czerwonkabartosz** [comment]
Look here - http://hapijs.com/api#serverextevents. By default, ext adds a prehandler to connection.

> sandbox - if set to 'plugin' when adding a request extension points the extension is only added to routes defined by the current plugin. Not allowed when configuring route-level extensions, or when adding server extensions. Defaults to 'connection' which applies to any route added to the connection the extension is added to.

**Comment by czerwonkabartosz** [comment]
Please check again these tests, because such a situation is not possible. For each connection configuration is added to `internals.configs`. It is not possible to replace the configuration. I understand that if there was an error with the lack of configuration, but not this problem.

**Comment by czerwonkabartosz** [comment]
@fknop Did you test it again ? Because it works stable for me.

**Pull request merged**
