### PR TITLE
Fix: Reply without modifying response when an error/exception is thrown from handler #9

### PR DESCRIPTION
**Pull request by vishalgheravada**
If statusCode is other than 200 it won't show the message "The results must be an array" & continue with the given response

### CODE REVIEW

**Comment by fknop** [comment]
Doesn't this line https://github.com/Atyantik/hapi-pagination/blob/cc2c0fabb4cc492241478d2d7048c1927c8f7023/lib/ext.js#L128 already handle what you want ?

**Comment by vishalgheravada** [comment]
When an exception is thrown from the handler, it is not handled properly & gives the following error:
https://github.com/fknop/hapi-pagination/issues/9

**Comment by vishalgheravada** [comment]
@fknop Any update on this?

**Comment by fknop** [comment]
I'll look into it today, I believe changing this line https://github.com/Atyantik/hapi-pagination/blob/cc2c0fabb4cc492241478d2d7048c1927c8f7023/lib/ext.js#L128 might just do the trick.

**Comment by vishalgheravada** [comment]
@fknop I have added appropriate test case to cover the scenario.
I was breaking when response is custom manipulated.
```
const response = reply({
    message: "Custom Error Message"
});
response.code(500);
```
The statusCode check problem solves it. Hope this can be now merged.

**Comment by fknop** [comment]
Just looked at your PR, instead of only 200 it should be 200 to 299 to cover all success codes.

Sorry if this took time, I'm busy at the moment!

**Comment by vishalgheravada** [comment]
@fknop Sorry for bit of delay. No Issue, I understand you are busy. 
I have updated the code and test-cases to support statusCode range 200-299.

Thanks

**Comment by fknop** [comment]
Published with 1.21.0

**Pull request merged**
