### PR TITLE
Setuping ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Hey @fknop! 

I set up for you a full CI with travis and coveralls to help you in the development, 
and as a statement of module quality.

I also modified two tests for which result was random (order of query string parameter)

Enjoy :smiley: 

Ps: Looking at your plugin I had some idea in mind and suggestion for a more dry code, 
and a more lightweight DSL. Tell me if you want to hear them

### CODE REVIEW

**Comment by fknop** [comment]
Hello @AdrieanKhisbe,

Thank you for that ! :smile:

> Ps: Looking at your plugin I had some idea in mind and suggestion for a more dry code,
> and a more lightweight DSL. Tell me if you want to hear them 

I'm open to suggestions !
I know the code is not really clean (I wrote it quickly to handle pagination in a school project). I had plan to clean it but it wasn't really a priority so far. 

Ps:

> I also modified two tests for which result was random (order of query string parameter)

Did you commit the tests ? I don't see them.

**Comment by AdrieanKhisbe** [comment]
I forgot to push them ^^

**Comment by AdrieanKhisbe** [comment]
I pushed them, and made a new PR.

I'll give a deeper look tomorrow or monde, and tell you then some sugestion.

(one to my mind: use one of `lodash` to build the user array. functional style :) )

**Comment by fknop** [comment]
Thank you again. I'm gonna read about Travis CI and other tools. I'm still new to this and don't know all these tools ! :smile:

**Comment by AdrieanKhisbe** [comment]
You're welcome =)
Good reading!

**Comment by AdrieanKhisbe** [comment]
Hello @fknop,

I took time to look further at your code, here are some suggestions:
- use `const` instead if `let` in most place (`lab -L` linter will tell you where)
- add a `Joi` schema to validate options 
- extract the pre handler functions in dedicated function. (avoiding the 240l function ^^)
- call to `next` with an error rather to throw a error: (`Hoek.assert` does)

also you can replace:

``` js
exports.register.attributes = {
    name: require('./package.json').name,
    version: require('./package.json').version
};
```

by 

``` js
exports.register.attributes = {
     pkg: require('../package.json')
};
```

**Comment by AdrieanKhisbe** [comment]
Ooops, should have pull before to dig in. :)
Sorryyyyy

Give a look to [Joi](https://github.com/hapijs/joi): 
You can refactor all [checkConfig](https://github.com/fknop/hapi-pagination/blob/master/lib/config.js#L96-L158) by using a schema :)

**Comment by fknop** [comment]
Hi ! Thanks I knew Joi but didn't even think about it ... That's great, I'll do that when I have time !

**Comment by AdrieanKhisbe** [comment]
:)
here is some example: https://github.com/AdrieanKhisbe/hapi-configue/blob/master/lib/configue.js#L65-L87

**Comment by fknop** [comment]
> use const instead if let in most place (lab -L linter will tell you where)
> add a Joi schema to validate options
> extract the pre handler functions in dedicated function. (avoiding the 240l function ^^)
> call to next with an error rather to throw a error: (Hoek.assert does)

I think it's all done ! I added some tests for the Joi validation. (Is there a way to make the validation simpler or it's the simpler it can be ? :smiley: ) 

I think I should probably split the pre handler and pre response into functions, what do you think ?

**Comment by AdrieanKhisbe** [comment]
Indeed it mught be better to split the `pre` s
I'll give a look to your refactor later and give you some feedback. (I'm busy at a meetup =))

**Comment by fknop** [comment]
No problem, I'll probably do that tomorrow anyway.

**Comment by fknop** [comment]
You can take a look :) !

https://github.com/fknop/hapi-pagination/tree/clean/refactor

**Pull request merged**
